### ISSUE TITLE
crossover energy specification

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#163] opened 2018-01-10 07:18 UTC
Hi, can someone please say something about the following:

Much like the crossover energy specified in the combined DINT-EleCa propagation module (CRPropa 3) in the example for [secondary photons](https://github.com/CRPropa/CRPropa3-notebooks/blob/master/secondaries/photons.v3.ipynb), is there a way to specify the crossover energy in combined CRPropa3 + DINT propagation (CRPropa 3.1)?

Also, now I am getting the following message iteratively when I run the simulation (1D simulation with injected protons enabling secondary photons and electrons) using CRPropa 3 + DINT
`DintPropagation: Energy too low -inf`

**Comment by cheiter** [comment] 2018-01-17 10:29
There is no module which performs a combined propagation with CRPropa and DINT. You first have to propagate the photons and electrons with the CRPropa EM interaction modules to a certain energy and collect them. These particles can then be turned over to DINT via e.g. the EMCascade module. 

In the past there was a module called PhotonOutputThreshold1D (commit: c2c9e47a597685fcff293e4f0321a147fe3e9bdb) where a threshold for photon and electron collection could be specified. It was replaced during the development because its functionality was adapted by other modules (like ParticleFilter (which was also removed) and EMCascade). Unfortunately the energy threshold function was not adapted.

The easiest way to realise a combined CRPropa-DINT propagation would be to add the energy threshold to the process function of EMCascade similar as it was realised in PhotonOutputThreshold1D, so only particles below the threshold are collected and prepared for DINT propagation.

Maybe your are trying to process a particle with DINT which energy is below a minimum energy threshold of DINT ? Do you know which particle throws the error ?

**Comment by saikat8018** [comment] 2018-01-17 10:42
Yes, I have been propagating the photons and electrons with the CRPropa EM interaction modules first. Then I am passing them onto the DINT propagation module. But I was not sure how should I specify the crossover energy. You have written, "...particles below the threshold are collected and prepared for DINT propagation...". Do you mean below or above? I may sound foolish, but I am a bit confused here.

I don't know exactly, which particle throws the error. I am propagating the secondary photons and electrons from primary protons.

**Comment by cheiter** [comment] 2018-01-17 11:06
In the current status of the EMCascade module no energy threshold is defined, so all photons and electrons turned over to the module are prepared for DINT propagation regardless of their energy.

You collect photons and electrons with PhotonOutput1D so these particles are not propagated with the CRPropa EM interaction modules, but gathered by the module just after their creation. In this case you would have a pure DINT EM propagation if you load this file into EMCascade.

Thats why I said you need to modify EMCascade to archive a combined propagation of CRPropa and DINT.

**Comment by saikat8018** [comment] 2018-01-17 11:17
Okay, you mean modifying EMcascade in the code? Sorry, I misunderstood. Is there some other way than modifying the code?

**Comment by cheiter** [comment] 2018-01-17 11:55
Unfortunately the original way I implemented to do so, via PhotonOutputThreshold1D has been removed.
I will check if there is a workaround but the quick solution is just change two lines in the code or check out the old PhotonOutputThreshold1D module and there you go.

**Comment by cheiter** [comment] 2018-01-17 12:22
This:
>> sim.add(MinimumEnergy( 10**13 * eV))
would throw all particles with energies below 10**13 eV out of your simulation. So its not the right way for your usecase.

>> I can see from the PhotonOutput1D output, the secondaries stored have energies typically 10** -7 * >> EeV i.e., ~ 10**11 * eV. But I guess, this problem is due to insufficiency in providing the energy >>threshold.
DINT should be fine with that energies, it has a minimum energy of 10 MeV according to the code, what do you mean with the problem is due to the missing threshold ?

**Comment by saikat8018** [comment] 2018-01-17 13:21
Okay then the error that DINT shows must be due to some other cause. Maybe because there are particles with energy lower than 10*MeV. But ehy is that happening?

**Comment by saikat8018** [comment] 2018-01-18 06:34
The error

> DintPropagation: Energy too low -inf

doesn't appear when I do a pure DINT EM propagation, i.e., I remove the CRPropa EM interaction modules, collect the secondary photons and electrons by `PhotonOutput1D(filename.txt)` and pass them to DINT propagation. 

Whereas the error occurs when I use the CRPropa EM interaction modules along with `PhotonOutput1D(filename.txt)` and then propagating by DINT which should also result in pure DINT propagation:

> You collect photons and electrons with PhotonOutput1D so these particles are not propagated with the CRPropa EM interaction modules, but gathered by the module just after their creation. In this case you would have a pure DINT EM propagation if you load this file into EMCascade.

**Comment by cheiter** [comment] 2018-01-18 09:14
Ok that seems like the EM interaction modules act on the produced photons and electrons at least in one propagation step before they are collected by PhotonOutput1D. 
In the output files do you have particles at energies below 10 MeV ? 
If yes can you backtrack which module produced these particles ?
I suppose not, but did you switch on the SynchrotronRadiation photon output ?

**Comment by saikat8018** [comment] 2018-01-18 10:05
Thank you very much for the patience and support. But, even after adding `sim.add(MinimumEnergy(10**13 *eV))` to the simulation chain, which should throw away all particles below this energy, why are particles below 10*MeV getting collected by `PhotonOutput1D`?

In the output file, I can see particles with energy ~ 10** -12 * EeV = 10**6 * eV. This particle has PDG MC Id 11, i.e. an electron. There are also electrons with zero energy produced too.  Not all particles are in that energy range, but I get the error in a loop, coming iteratively throughout the time DINT runs. Nothing is written in the DINT output file.

`SynchrotronRadiation` is not added to the simulation. Here is a minimal script of the simulation for primary iron nuclei:
[script.txt](https://github.com/CRPropa/CRPropa3/files/1642376/script.txt)

**Comment by cheiter** [comment] 2018-02-27 14:43
Sorry about the delay, here is a minimum working example of a workaround to perform a CRPropa-DINT combined propagation:

`from crpropa import *

class MyModule(Module): 
    Ethr = 0.001*EeV
    out = EMCascade()
    def process(self,c):
        if (c.current.getEnergy() < self.Ethr):
            self.out.process(c)

sim = ModuleList()
sim.add(SimplePropagation())
sim.add(Redshift())
sim.add(EMPairProduction(CMB,True))
sim.add(EMPairProduction(IRB_Finke10,True))
sim.add(EMPairProduction(URB_Protheroe96,True))
sim.add(EMInverseComptonScattering(IRB_Finke10,True))
sim.add(EMInverseComptonScattering(CMB,True))
sim.add(EMInverseComptonScattering(URB_Protheroe96,True))
sim.add(EMTripletPairProduction(CMB,True))
sim.add(EMTripletPairProduction(IRB_Finke10,True))
sim.add(EMTripletPairProduction(URB_Protheroe96,True))
myModule = MyModule()
myModule.Ethr = 1*EeV
sim.add(myModule)
obs = Observer()
obs.add(ObserverPoint())
obs.add(ObserverInactiveVeto())
t = TextOutput("EM_above_threshold.txt",Output.Event1D)
obs.onDetection(t)
source = Source()
source.add(SourcePosition(Vector3d(4,0,0)*Mpc))
source.add(SourceRedshift1D())
source.add(SourceParticleType(22))
source.add(SourceEnergy(50*EeV))
sim.add(obs)
sim.run(source,10,True)
myModule.out.save("EM_below_threshold.txt")
myModule.out.runCascade("DINT_output.txt")`

Simply define a module which turns all EM particles below a specified threshold energy over to the EMCascade module. 
For more information creating you own modules in CRPropa please refer to 
[Extending CRPropa](https://github.com/CRPropa/CRPropa3/wiki/Extending-CRPropa)

**Comment by saikat8018** [comment] 2018-02-28 11:30
Can you please explain to me how you are specifying the cutoff by defining a new module MyModule( ) because there are two threshold energy defined, about which I am confused.

In the beginning, there is

> class MyModule(Module):
> Ethr = 0.001*EeV

And later, there is

> myModule = MyModule()
> myModule.Ethr = 1*EeV

Also, I can understand from the script that all particles above Ethr will be propagated through CRPropa EM interaction modules. But for particles below Ethr, they should be propagated via DINT, is that done by the following part?

> myModule.out.save("EM_below_threshold.txt")
> myModule.out.runCascade("DINT_output.txt")

**Comment by cheiter** [comment] 2018-02-28 11:53
Oh you're right .. but the later assignment is the one which defines the threshold in this case.

Correct the `runCascade()` function will start the DINT propagation of the particles gathered via `EMCascade`. The `save()` function gives you a data file of the gathered particles before DINT propagation in the DINT binning scheme.

**Comment by saikat8018** [comment] 2018-02-28 12:19
Thank you very much for your patience.
So, maybe you mean to say that Ethr should be the same in both cases? Otherwise, if the later one defines the threshold, what is the first one defined for?

**Comment by cheiter** [comment] 2018-02-28 17:05
I just wrote a quick solution the first is just to initialize the variable in the class and the second to assign it. If you want a more elegant code you can define the threshold in the initialization of the class.

Yes, "EM_above_threshold.txt" contains the EM particles detected at the observer which have energies above the threshold energy and are propagated with the CRPropa EM interaction modules.

**Comment by saikat8018** [comment] 2018-03-01 06:28
Okay, thank you very much Christopher. This has immensely helped me.

**Closed** 2018-03-01 11:49 UTC
