### ISSUE TITLE
Error: Linking CXX executable testGalacticMagneticLens

### ISSUE THREAD

**Issue by CRPropaUser** [CRPropa/CRPropa3#112] opened 2017-01-27 20:43 UTC
cmake -DCMAKE_INSTALL_PREFIX=/CP -DFFTW3F_LIBRARY=/fftw-3.3.5/lib/libfftw3f.a -DFFTW3F_INCLUDE_DIR=/fftw-3.3.5/include/ ..
-- The Fortran compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working Fortran compiler: /bin/f95
-- Check for working Fortran compiler: /bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /bin/f95 supports Fortran 90
-- Checking whether /bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use --as-needed linker flags!
-- Build Type: Release
-- CRPropa version: 3.0-124-gce05ea9 ce05ea931edb92da62b6565afedf0b0fe6bf20ab refs/heads/master
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
Using provided EIGEN
-- ROOT: Found!
--   CFlags:      -pthread -m64 -I/ROOT/v5.34.36/include/root
--   Libs:        -L/ROOT/v5.34.36/lib/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP Fortran flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Google perftools: NOT Found!
--   Include: GOOGLE_PERFTOOLS_INCLUDE_DIR-NOTFOUND
-- FFTW3 with single precision (FFTW3F): Found!
--   Include:     /fftw-3.3.5/include
--   Library:     /fftw-3.3.5/lib/libfftw3f.a
-- Quimby: NOT Found!
--   Include:     QUIMBY_INCLUDE_DIR-NOTFOUND
--   Library:     QUIMBY_LIBRARY-NOTFOUND
-- SAGA: NOT Found!
--   Include:     SAGA_INCLUDE_DIR-NOTFOUND
--   Library:     SAGA_LIBRARY-NOTFOUND
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- muParser: NOT Found!
--   Include:     MUPARSER_INCLUDE_DIR-NOTFOUND
--   Library:     MUPARSER_LIBRARY-NOTFOUND
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /HDF5/1.8.17/lib/libhdf5.so;/Szip/2.1/lib/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libpthread.so (found version "1.8.17") found components:  C 
-- Use absolute RPATH /CP/lib
-- Downloading data file from crpropa.desy.de ~ 50 MB
-- Extracting data file
-- Found PythonInterp: /Python/2.7.12/bin/python (found version "2.7.12") 
-- Found PythonLibs: /Python/2.7.12/lib/libpython2.7.so (found version "2.7.12") 
-- Found SWIG: /SWIG/3.0.10/bin/swig (found version "3.0.10") 
-- Python: Found!
--   Version:     2.7/27
--   Executeable: /Python/2.7.12/bin/python
--   Include:     /Python/2.7.12/include/python2.7
--   Library:     /Python/2.7.12/lib/libpython2.7.so
--   Site-package directory: /CP/lib/python2.7/site-packages
-- Found numpy headers in /Python/2.7.12/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written to:  /CP/build

make
Scanning dependencies of target healpix_base
[  1%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/error_handling.cc.o
[  2%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/geom_utils.cc.o
[  3%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_base.cc.o
[  3%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_tables.cc.o
[  4%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/pointing.cc.o
[  5%] Linking CXX static library libhealpix_base.a
[  5%] Built target healpix_base
Scanning dependencies of target kiss
[  5%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/logger.cpp.o
[  6%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/path.cpp.o
[  7%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/string.cpp.o
[  7%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/uuid.cpp.o
[  8%] Linking CXX static library libkiss.a
[  8%] Built target kiss
Scanning dependencies of target pugixml
[  9%] Building CXX object libs/pugixml/CMakeFiles/pugixml.dir/pugixml.cpp.o
[  9%] Linking CXX static library libpugixml.a
[  9%] Built target pugixml
Scanning dependencies of target HepPID
[  9%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleIDMethods.cc.o
[ 10%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleName.cc.o
[ 11%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/Version.cc.o
[ 11%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateEvtGen.cc.o
[ 12%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateGeanttoPDT.cc.o
[ 13%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateHerwig.cc.o
[ 13%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateIsajet.cc.o
[ 14%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDG.cc.o
[ 15%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDTtoGeant.cc.o
[ 15%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePythia.cc.o
[ 16%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateQQ.cc.o
[ 17%] Linking CXX static library libHepPID.a
[ 17%] Built target HepPID
Scanning dependencies of target sophia
[ 18%] Building Fortran object libs/sophia/CMakeFiles/sophia.dir/sophia_interface.f.o
[ 19%] Linking Fortran static library libsophia.a
[ 19%] Built target sophia
Scanning dependencies of target dint
[ 20%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/advance.cpp.o
[ 20%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/background.cpp.o
[ 21%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/binfread.cpp.o
[ 22%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/check.cpp.o
[ 22%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/cvector.cpp.o
[ 23%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/decay.cpp.o
[ 24%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/deriv.cpp.o
[ 24%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/error.cpp.o
[ 25%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/final.cpp.o
[ 26%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/fold.cpp.o
[ 26%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/frag.cpp.o
[ 27%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/gauleg.cpp.o
[ 28%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/inject.cpp.o
[ 29%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/io_util.cpp.o
[ 29%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/load.cpp.o
[ 30%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/math_util.cpp.o
[ 31%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prepare.cpp.o
[ 31%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prop_second.cpp.o
[ 32%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/rate.cpp.o
[ 33%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/spectrum.cpp.o
[ 33%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/sync.cpp.o
[ 34%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/vector.cpp.o
[ 35%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/DintEMCascade.cpp.o
[ 35%] Linking CXX static library libdint.a
[ 35%] Built target dint
Scanning dependencies of target eleca
[ 36%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Common.cpp.o
[ 37%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/EnergyLoss.cpp.o
[ 38%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Particle.cpp.o
[ 38%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Process.cpp.o
[ 39%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Propagation.cpp.o
[ 40%] Linking CXX static library libeleca.a
[ 40%] Built target eleca
Scanning dependencies of target crpropa
[ 41%] Building CXX object CMakeFiles/crpropa.dir/src/Random.cpp.o
[ 41%] Building CXX object CMakeFiles/crpropa.dir/src/Clock.cpp.o
[ 42%] Building CXX object CMakeFiles/crpropa.dir/src/ModuleList.cpp.o
[ 43%] Building CXX object CMakeFiles/crpropa.dir/src/Module.cpp.o
[ 43%] Building CXX object CMakeFiles/crpropa.dir/src/Candidate.cpp.o
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/EmissionMap.cpp.o
[ 45%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleState.cpp.o
[ 45%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleID.cpp.o
[ 46%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleMass.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/ProgressBar.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/Cosmology.cpp.o
[ 48%] Building CXX object CMakeFiles/crpropa.dir/src/Source.cpp.o
[ 49%] Building CXX object CMakeFiles/crpropa.dir/src/Common.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonBackground.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonPropagation.cpp.o
[ 51%] Building CXX object CMakeFiles/crpropa.dir/src/GridTools.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/XmlExecute.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/module/BreakCondition.cpp.o
[ 53%] Building CXX object CMakeFiles/crpropa.dir/src/module/Boundary.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/Observer.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/SimplePropagation.cpp.o
[ 55%] Building CXX object CMakeFiles/crpropa.dir/src/module/PropagationCK.cpp.o
[ 56%] Building CXX object CMakeFiles/crpropa.dir/src/module/ElectronPairProduction.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/NuclearDecay.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoPionProduction.cpp.o
[ 58%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoDisintegration.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/ElasticScattering.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/Redshift.cpp.o
[ 60%] Building CXX object CMakeFiles/crpropa.dir/src/module/Output.cpp.o
[ 61%] Building CXX object CMakeFiles/crpropa.dir/src/module/TextOutput.cpp.o
[ 61%] Building CXX object CMakeFiles/crpropa.dir/src/module/ParticleCollector.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o
[ 63%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputShell.cpp.o
[ 63%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputROOT.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputCRPropa2.cpp.o
[ 65%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonOutput1D.cpp.o
[ 66%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonEleCa.cpp.o
[ 66%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMCascade.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMPairProduction.cpp.o
[ 68%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMDoublePairProduction.cpp.o
[ 68%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMTripletPairProduction.cpp.o
[ 69%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMInverseComptonScattering.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/module/SynchrotronRadiation.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/module/Tools.cpp.o
[ 71%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticField.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticFieldGrid.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/JF12Field.cpp.o
[ 73%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/PshirkovField.cpp.o
[ 74%] Building CXX object CMakeFiles/crpropa.dir/src/Version.cpp.o
[ 75%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/MagneticLens.cpp.o
[ 75%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ModelMatrix.cpp.o
[ 76%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/Pixelization.cpp.o
[ 77%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ParticleMapsContainer.cpp.o
[ 77%] Linking CXX shared library libcrpropa.so
[ 77%] Built target crpropa
Scanning dependencies of target gtest
[ 77%] Building CXX object libs/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 78%] Linking CXX static library libgtest.a
[ 78%] Built target gtest
Scanning dependencies of target gtest_main
[ 79%] Building CXX object libs/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 79%] Linking CXX static library libgtest_main.a
[ 79%] Built target gtest_main
Scanning dependencies of target testGalacticMagneticLens
[ 80%] Building CXX object CMakeFiles/testGalacticMagneticLens.dir/test/testMagneticLens.cpp.o
[ 80%] Linking CXX executable testGalacticMagneticLens
libcrpropa.so: undefined reference to `ompi_mpi_cxx_op_intercept'
libcrpropa.so: undefined reference to `MPI::Win::Free()'
libcrpropa.so: undefined reference to `MPI::Datatype::Free()'
libcrpropa.so: undefined reference to `MPI::Comm::Comm()'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[2]: *** [testGalacticMagneticLens] Fehler 1
make[1]: *** [CMakeFiles/testGalacticMagneticLens.dir/all] Fehler 2
make: *** [all] Fehler 2

**Comment by adundovi** [comment] 2017-01-28 23:01
Could you please write more details: is this a new behaviour on some old system that already had CRPropa3 installed, or you tried to compile CRPropa on a new computer/system? If the latter is the case, probably something is wrong with the OpenMPI installation where linker cannot find proper libraries. In both cases, it would be helpful to know what system is in question?

**Comment by DavidWit** [comment] 2017-01-29 00:40
The latter is the case. 
It is Centos 7.3.
How can I check the OpenMPI installation?

**Comment by adundovi** [comment] 2017-01-29 10:48
On second thought, I don't know why there is a need for OpenMPI (it is not the same thing as OpenMP) and I don't see any headers where we use its libraries... Maybe cmake found OpenMPI's compilers path and not the regular ones. Please check that the found compiler (/bin/c++) is not OpenMPI's one. You can do it for example with the following command:
```
$ /bin/c++ -E -x c++ - -v < /dev/null 2>&1 | grep openmpi
```
in case of OpenMPI version of it you will see some output, otherwise, there will be no output. If the former is the case, you will have to set a path to the clean version of c++ compiler and complain to administrators of the system why they changed default paths (because this is not expected setup, at least not on a CentOS system) :-)

**Comment by CRPropaUser** [comment] 2017-01-29 14:16
The latter is the case. I see no output.

**Comment by adundovi** [comment] 2017-01-29 19:45
I've checked the build procedure on a fresh installation of Centos 7 (all packages from default repositories) and it worked flawlessly. Hence, I would say that the problem is in your particular system - if it is a shared system maybe someone changed library paths which include OpenMPI by default and then it is interfering with a CRPropa installation. To see exactly what is incorporated in your build procedure, add the following option to cmake:
```
cmake .. -DCMAKE_VERBOSE_MAKEFILE=True
```
re-build and then paste the output in the part where it fails. It should give us more details what options your compiler uses.

btw try to use the newest version of CRPropa (git pull)

**Comment by CRPropaUser** [comment] 2017-01-29 22:43
Thank you for your help and support. 
Here is the output in the part where it fails:


Scanning dependencies of target testGalacticMagneticLens
make[2]: Leaving directory `/foo/CRPropa3_290117/build'
make -f CMakeFiles/testGalacticMagneticLens.dir/build.make CMakeFiles/testGalacticMagneticLens.dir/build
make[2]: Entering directory `/foo/CRPropa3_290117/build'
[ 81%] Building CXX object CMakeFiles/testGalacticMagneticLens.dir/test/testMagneticLens.cpp.o
/bin/c++   -DCRPROPA_HAVE_FFTW3F -DCRPROPA_HAVE_HDF5 -DCRPROPA_HAVE_ROOT -DCRPROPA_HAVE_ZLIB -DCRPROPA_INSTALL_PREFIX=\"/foo/install/CP3_181116\" -I/foo/CRPropa3_290117/libs/gtest/include -I/foo/CRPropa3_290117/include -I/foo/CRPropa3_290117/libs/kiss/include -I/foo/CRPropa3_290117/libs/pugixml -I/foo/CRPropa3_290117/libs/HepPID/include -I/foo/CRPropa3_290117/libs/sophia -I/foo/CRPropa3_290117/libs/dint/include -I/foo/CRPropa3_290117/libs/EleCa/include -I/foo/CRPropa3_290117/libs/eigen3 -I/foo/CRPropa3_290117/libs/healpix_base/include -I/software/FFTW/3.3.4-gompi-2016b/include -I/foo/CRPropa3_290117/libs/zstream-cpp -I/software/HDF5/1.8.17-foss-2016b/include -I/software/OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1/include -I/software/ScaLAPACK/2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1/include -I/software/zlib/1.2.8-foss-2016b/include -I/software/Szip/2.1-foss-2016b/include -I/software/Python/2.7.12-foss-2016b/include/python2.7 -I/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/core/include  -pthread -m64 -I/software/ROOT/v5.34.36-foss-2016b-Python-2.7.12/include/root -fopenmp -O3 -DNDEBUG   -o CMakeFiles/testGalacticMagneticLens.dir/test/testMagneticLens.cpp.o -c /foo/CRPropa3_290117/test/testMagneticLens.cpp
[ 81%] Linking CXX executable testGalacticMagneticLens
/software/CMake/3.6.2-foss-2016b/bin/cmake -E cmake_link_script CMakeFiles/testGalacticMagneticLens.dir/link.txt --verbose=1
/bin/c++    -pthread -m64 -I/software/ROOT/v5.34.36-foss-2016b-Python-2.7.12/include/root -fopenmp -O3 -DNDEBUG   -Wl,--as-needed -L/software/ROOT/v5.34.36-foss-2016b-Python-2.7.12/lib/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic  CMakeFiles/testGalacticMagneticLens.dir/test/testMagneticLens.cpp.o  -o testGalacticMagneticLens -rdynamic libcrpropa.so libs/gtest/libgtest.a libs/gtest/libgtest_main.a -lpthread libs/kiss/libkiss.a libs/pugixml/libpugixml.a libs/HepPID/libHepPID.a libs/sophia/libsophia.a -lgfortran libs/dint/libdint.a libs/EleCa/libeleca.a libs/healpix_base/libhealpix_base.a -lCore -lRIO -lTree -Wl,-Bstatic -lfftw3f -Wl,-Bdynamic -lz -lhdf5 -lsz -lz -lhdf5 -lsz -ldl -lm -lpthread libs/gtest/libgtest.a -lpthread -lgfortran -lquadmath -Wl,-rpath,/foo/CRPropa3_290117/build 
libcrpropa.so: undefined reference to `ompi_mpi_cxx_op_intercept'
libcrpropa.so: undefined reference to `MPI::Win::Free()'
libcrpropa.so: undefined reference to `MPI::Datatype::Free()'
libcrpropa.so: undefined reference to `MPI::Comm::Comm()'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[2]: *** [testGalacticMagneticLens] Fehler 1
make[2]: Leaving directory `/foo/CRPropa3_290117/build'
make[1]: *** [CMakeFiles/testGalacticMagneticLens.dir/all] Fehler 2
make[1]: Leaving directory `/foo/CRPropa3_290117/build'
make: *** [all] Fehler 2

**Comment by adundovi** [comment] 2017-01-29 23:26
It looks that you have FFTW version which is compiled with OpenMPI while CRPropa doesn't support MPI, thus you will not gain anything with MPI-enabled FFTW as far as I know. I would drop the current version of it and try the "standard" one, either from the distribution's repository, or one manually compiled.

BTW. To avoid this and similar problems, try to follow [this](https://github.com/CRPropa/CRPropa3/wiki/Installation) guide where everything is more isolated and reproducible. Relying on 3rd-party manually compiled dependencies is always risky and can lead to unforeseen results.

**Comment by CRPropaUser** [comment] 2017-02-05 11:56
I will give you new feedback, when the admin has done the installation.
I'm sorry about the delay, but the admin is not very fast...

**Comment by TobiasWinchen** [comment] 2017-10-26 15:13
I assume the issue is fixed by now? Please reopen if there is still a problem.

**Closed** 2017-10-26 15:13 UTC
