### ISSUE TITLE
Extending of CRPropa modules in Python shell leads to segfault

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#27] opened 2015-06-03 15:40 UTC
Examples of extending CRPropa given [here](https://github.com/CRPropa/CRPropa3/wiki/Extending%20CRPropa) are leading to segmentation faults when used in Python interactive shell.

Steps to reproduce:
1. run python shell (tried python 2.7.9 and 2.6.6)
2. import crpropa: `from crpropa import *`
3. paste an example to shell:
```python
class MyModule(Module):
    """ Reduces the cosmic ray energy by 10% in each step """
    def process(self, c):
        c.current.setEnergy(c.current.getEnergy() * 0.9)

m = ModuleList()
m.add(MyModule())

c = Candidate()
c.current.setEnergy(10)
m.process(c)
```
4. segmentation fault, trace:
```
 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x0000003b320c7eea in waitpid () from /lib64/libc.so.6
#1  0x0000003b32043a4b in do_system () from /lib64/libc.so.6
#2  0x0000003b3446dff2 in TUnixSystem::StackTrace() () from /usr/lib64/root/libCore.so.5.34
#3  0x0000003b3447025c in TUnixSystem::DispatchSignals(ESignals) () from /usr/lib64/root/libCore.so.5.34
#4  <signal handler called>
#5  0x0000003b3208a9da in strlen () from /lib64/libc.so.6
#6  0x0000003b3e491f7f in PyString_FromFormatV () from /lib64/libpython2.7.so.1.0
#7  0x0000003b3e4ec01c in PyErr_Format () from /lib64/libpython2.7.so.1.0
#8  0x0000003b3e4862e5 in PyObject_GetAttr () from /lib64/libpython2.7.so.1.0
#9  0x0000003b3e486534 in PyObject_GetAttrString () from /lib64/libpython2.7.so.1.0
#10 0x0000003b3e44aead in PyObject_CallMethod () from /lib64/libpython2.7.so.1.0
#11 0x00007f49655a96a3 in SwigDirector_Module::process (this=0x1d5f660, candidate=0x1d90da0) at /home/a/crpropa_virtenv/crpropa3_build/build/crpropa_wrap.cxx:6968
#12 0x00007f4964f0553b in crpropa::ModuleList::process (this=0x1a258b0, candidate=0x1d90da0) at /home/a/crpropa_virtenv/crpropa3_build/src/ModuleList.cpp:47
#13 0x00007f496566d5ad in _wrap_ModuleList_process (self=0x7f496c31a1f0, args=0x7f496c312610) at /home/a/crpropa_virtenv/crpropa3_build/build/crpropa_wrap.cxx:62139
#14 0x0000003b3e4e290e in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#15 0x0000003b3e4e3704 in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#16 0x0000003b3e4e3829 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#17 0x0000003b3e4fcb5f in run_mod () from /lib64/libpython2.7.so.1.0
#18 0x0000003b3e4febba in PyRun_InteractiveOneFlags () from /lib64/libpython2.7.so.1.0
#19 0x0000003b3e4fed9e in PyRun_InteractiveLoopFlags () from /lib64/libpython2.7.so.1.0
#20 0x0000003b3e4ff42e in PyRun_AnyFileExFlags () from /lib64/libpython2.7.so.1.0
#21 0x0000003b3e511141 in Py_Main () from /lib64/libpython2.7.so.1.0
#22 0x0000003b32020790 in __libc_start_main () from /lib64/libc.so.6
#23 0x0000000000400729 in _start ()
===========================================================

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#5  0x0000003b3208a9da in strlen () from /lib64/libc.so.6
#6  0x0000003b3e491f7f in PyString_FromFormatV () from /lib64/libpython2.7.so.1.0
#7  0x0000003b3e4ec01c in PyErr_Format () from /lib64/libpython2.7.so.1.0
#8  0x0000003b3e4862e5 in PyObject_GetAttr () from /lib64/libpython2.7.so.1.0
#9  0x0000003b3e486534 in PyObject_GetAttrString () from /lib64/libpython2.7.so.1.0
#10 0x0000003b3e44aead in PyObject_CallMethod () from /lib64/libpython2.7.so.1.0
#11 0x00007f49655a96a3 in SwigDirector_Module::process (this=0x1d5f660, candidate=0x1d90da0) at /home/a/crpropa_virtenv/crpropa3_build/build/crpropa_wrap.cxx:6968
#12 0x00007f4964f0553b in crpropa::ModuleList::process (this=0x1a258b0, candidate=0x1d90da0) at /home/a/crpropa_virtenv/crpropa3_build/src/ModuleList.cpp:47
#13 0x00007f496566d5ad in _wrap_ModuleList_process (self=0x7f496c31a1f0, args=0x7f496c312610) at /home/a/crpropa_virtenv/crpropa3_build/build/crpropa_wrap.cxx:62139
#14 0x0000003b3e4e290e in PyEval_EvalFrameEx () from /lib64/libpython2.7.so.1.0
#15 0x0000003b3e4e3704 in PyEval_EvalCodeEx () from /lib64/libpython2.7.so.1.0
#16 0x0000003b3e4e3829 in PyEval_EvalCode () from /lib64/libpython2.7.so.1.0
#17 0x0000003b3e4fcb5f in run_mod () from /lib64/libpython2.7.so.1.0
#18 0x0000003b3e4febba in PyRun_InteractiveOneFlags () from /lib64/libpython2.7.so.1.0
#19 0x0000003b3e4fed9e in PyRun_InteractiveLoopFlags () from /lib64/libpython2.7.so.1.0
#20 0x0000003b3e4ff42e in PyRun_AnyFileExFlags () from /lib64/libpython2.7.so.1.0
#21 0x0000003b3e511141 in Py_Main () from /lib64/libpython2.7.so.1.0
#22 0x0000003b32020790 in __libc_start_main () from /lib64/libc.so.6
#23 0x0000000000400729 in _start ()
===========================================================

Segmentation fault (core dumped)
```

It seems that every call to a method which is doing something with object crafted in Python leads to segfault: .process(), getCandidate() and so on.

**Comment by DavidWalz** [comment] 2015-06-04 07:53
Ok, I can reproduce this.
It seems to be an ownership problem. Releasing ownership of the new module from the python side seems to do the trick.
```python
class MyModule(Module):
    """ Reduces the cosmic ray energy by 10% in each step """
    def process(self, c):
        c.current.setEnergy(c.current.getEnergy() * 0.9)

a = MyModule()
a.disown()
m = ModuleList()
m.add(a)

c = Candidate()
c.current.setEnergy(10)
m.process(c)
```

I don't know if there's a way to automatize this. If not, I can update the wiki accordingly.

**Comment by adundovi** [comment] 2015-06-04 19:14
Yes, this trick solves the problem. This situation is maybe a corner case (nobody actually write classes inside Python shell), hence not so important, but maybe the same problem arise using IPython notebooks which would become an issue. I can look into it, but not at the moment.

**Comment by DavidWalz** [comment] 2015-08-01 20:22
The [galactic trajectory example notebook](http://nbviewer.ipython.org/github/CRPropa/CRPropa3-notebooks/blob/master/galactic_trajectories/galactic_trajectories.ipynb) seg-faults, even with disown.

**Comment by TobiasWinchen** [comment] 2015-08-04 12:17
I cannot reproduce a segfault, but get a 'Swig::DirectorMethodException' from the example. The problem is probably unrelated, as this exception is caused by the unsupported division of the Vector with a float in line 28: Replacing "v = c.current.getPosition() / kpc " with " v = c.current.getPosition() " fixes the problem. However, we probably should support the division of vectors by floats.

**Comment by DavidWalz** [comment] 2015-08-04 15:02
True. This likely due to the -builtin option, since vector / float division was possible before.
I'll close this issue since we know how to get around it with disown() and open another for vector division.

**Closed by DavidWalz** 2015-08-04 15:02 UTC

**Comment by geromueller** [comment] 2015-08-04 15:39
Hi, just disowning may introduce other problems, especially when the python class contains resources. The best way is to keep the module instance in scope until the module list has finished. In the initial example, simple doing the "a = MyModule()" and not ".add(MyModule())" is enough.
