### ISSUE TITLE
run with DINT crashes

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#18] opened 2014-08-14 14:06 UTC
When running a 1D simulation with secondary gamma (DINT) the code crashes.
The module is called this way:
```
phot1 = PhotonDINT1D('test-dint.txt')
...
m.add(Observer1D())
m.add(EventOutput1D(OutputName))
m.add(phot1)
```
I tried:
  - running crpropa with only one thread
  - calling 	```prop_second()``` in PhotoDINT1D.cpp with ```#pragma omp critical```
The problem always persists. Sometimes the run lasts a bit longer and I get some photon output, but not in general.

The full error message can be seen here:
http://pastebin.com/jHCwGZS3

**Comment by TobiasWinchen** [comment] 2015-08-12 15:00
I close this bug because of the following reasons:
 * I cannot reproduce this behavior. 
 * The bug is quite old.
 * The usage of the PhotonDINT1D Module should be discouraged and the module should probably be removed as it is slow compared to propagating the secondaries in a second step.

**Closed by TobiasWinchen** 2015-08-12 15:00 UTC
