### ISSUE TITLE
Units ignored in constructor default arguments when using SWIG_BUILTIN = off

### ISSUE THREAD

**Issue by DavidWalz** [CRPropa/CRPropa3#42] opened 2015-09-24 08:34 UTC
Constructor
```c++
SimplePropagation(double minStep = 0, double maxStep = 10 * Mpc)
```

with SWIG_BUILTIN = off
```python
s = SimplePropagation()
s.getDescription()
>>> 'Simple Propagation: Step size = 0 - 3.24078e-22 Mpc'
```

with SWIG_BUILTIN = on
```python
s = SimplePropagation()
s.getDescription()
>>> 'Simple Propagation: Step size = 0 - 10 Mpc'
```

This breaks our notebook-examples as they do not terminate in reasonable time.

**Comment by rafaelab** [comment] 2015-09-24 11:31
Related to this, make test gets stuck at "Start 12: testSimulationExecution" with SWIG_BUILTIN=Off.
With SWIG_BUILTIN=On, it fails in "11/12 Test #11: testMagneticLensPythonInterface ...***Failed    4.78 sec".

**Comment by DavidWalz** [comment] 2015-09-24 12:04
testSimulationExecution.py is not stuck, with 10m propagation steps it just takes long to finish :)

**Comment by adundovi** [comment] 2015-10-22 08:48
@rafaelab: testMagneticLensPythonInterface is fixed (there was a typo in a method name)
@DavidWalz: I cannot reproduce:
With `bultin`
```
>>> from crpropa import *
>>> s = SimplePropagation()
>>> s.getDescription()
'Simple Propagation: Step size = 0 - 10 Mpc'
```
Without `builtin`:
```
>>> from crpropa import *
>>> s = SimplePropagation()
>>> s.getDescription()
'Simple Propagation: Step size = 0 - 10 Mpc'
```
And `12/12 Test #12: testSimulationExecution ...........   Passed    0.72 sec` passes in both cases.

**Comment by DavidWalz** [comment] 2015-10-23 10:47
This could be a new SWIG "feature". I'm on 
SWIG Version 3.0.7
gcc (GCC) 5.2.0
Python 2.7.10

**Comment by DavidWalz** [comment] 2015-10-23 10:58
This is the proxy class from crpropy.py
```python
class SimplePropagation(Module):
    def __init__(self, minStep=0, maxStep=10):
```

**Comment by adundovi** [comment] 2015-10-23 14:25
This is caused by SWIG 3.0.7 (or 3.0.6). Here is a relevant part of the diff in crpropa.py between SWIG 3.0.7 and 3.0.5 where this thing works:

```
3953c3935
<     def __init__(self, minStep=0, maxStep=10):
---
>     def __init__(self, *args):
3955c3937
<         __init__(crpropa::SimplePropagation self, double minStep=0, double maxStep=10) -> SimplePropagation
---
>         __init__(crpropa::SimplePropagation self, double minStep=0, double maxStep) -> SimplePropagation
3959c3941
<         this = _crpropa.new_SimplePropagation(minStep, maxStep)
---
>         this = _crpropa.new_SimplePropagation(*args)
```

It seems that before 3.0.6 there was [a bug](https://github.com/swig/swig/pull/294) which is now fixed and the fix exposed this problem which evidently leads to another bug in which "Mpc" part in "10 * Mpc" is ignored.

We have several choices:

1. set the `builtin`, where the bug doesn't occur, as default (and fix remaining bugs with it - I already fixed most of reported ones) - this should be our long term goal because `builtin` removes a big layer of complexity from the SWIG wrapper and thus lower the chances for bugs in this interface
2. temporarily override the default arguments in this function from Python until the bug is fixed
3. ask users to put `maxStep` as mandatory in `SimplePropagation( maxStep = 10*Mpc )` (until the bug is fixed)
4. require <= 3.0.5 version of SWIG (until the bug is fixed)

The given order of choices is what I would suggest.

**Comment by DavidWalz** [comment] 2015-10-28 08:24
Since it might take some time for this to be fixed in SWIG, I would also advocate for using -builtin, at least as default.
Are there some remaining issues?

**Comment by geromueller** [comment] 2015-10-29 08:17
A better way is to use overloaded constructurs, e.g. provide three constructors:

SimplePropagation()
SimplePropagation(double minStep)
SimplePropagation(double minStep, double maxStep)

Gero

**Comment by adundovi** [comment] 2015-11-01 14:45
Is there a reason, besides this bug, to use overloaded constructors instead of default arguments? Default arguments are a legitimate way of programming in Cpp and in our case it simplifies the code and increase the readability, or there are downsides of it? Maybe due to consistency with other parts of code?

**Comment by geromueller** [comment] 2015-11-01 15:04
Yes. Overloading is the only way to change default values without
recompilation of the calling functions.
But, i guess, this is not very important for us.

Am 01.11.2015 um 15:45 schrieb Andrej Dundovic:

**Comment by adundovi** [comment] 2015-11-01 15:24
But how do we accomplish that (to avoid recompilation of the module) because in the constructor without arguments we again need to hard code some default values hence recompilation is unavoidable? Or is there another approach? I'm just asking because of plain curiosity.

**Comment by geromueller** [comment] 2015-11-01 15:26
"without recompilation of the calling functions". So, yes the moculde
need to be recompiled. But e.g. the SWIG interface or some other C++
code needs to recompilation.
Using default arguments in the declaration (.h Files) means, these
values are stored in the calling object code.

Am 01.11.2015 um 16:24 schrieb Andrej Dundovic:

**Comment by adundovi** [comment] 2015-11-01 15:28
Ok, I didn't get it first time but now it's clear. Thank you :-)

**Closed** 2016-02-02 15:50 UTC
