### ISSUE TITLE
basic installation error

### ISSUE THREAD

**Issue by stamerra** [CRPropa/CRPropa3#132] opened 2017-08-16 18:03 UTC
Following installation instructions  https://github.com/CRPropa/CRPropa3/wiki/Installation 
I get stuck in the make procedure, getting following error.
Probably a basic error from newbies; btw any help is appreciated. 

OsX 10.11.6  - python 2.74

[ 84%] Linking CXX executable testBreakCondition
clang: warning: argument unused during compilation: '-pthread'
[ 84%] Built target testBreakCondition
[ 84%] Building CXX object CMakeFiles/testOutput.dir/test/testOutput.cpp.o
[ 85%] Linking CXX executable testOutput
clang: warning: argument unused during compilation: '-pthread'
[ 85%] Built target testOutput
[ 86%] Building CXX object CMakeFiles/testPropagation.dir/test/testPropagation.cpp.o
[ 86%] Linking CXX executable testPropagation
clang: warning: argument unused during compilation: '-pthread'
[ 86%] Built target testPropagation
[ 87%] Generating crpropa_wrap.cxx
swig error : Unrecognized option /usr/include
swig error : Unrecognized option /usr/local/opt/szip/include
Use 'swig -help' for available options.
make[2]: *** [crpropa_wrap.cxx] Error 1
make[1]: *** [CMakeFiles/crpropa-swig.dir/all] Error 2
make: *** [all] Error 2

**Comment by adundovi** [comment] 2017-08-17 17:34
Can you also write versions of other relevant packages: swig and gcc (or clang)?

**Comment by stamerra** [comment] 2017-08-17 20:38
Here the info:

```
SWIG Version 3.0.12
Compiled with clang++ [x86_64-apple-darwin15.6.0]
Configured options: +pcre

```
and for gcc:

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

```

**Comment by adundovi** [comment] 2017-08-18 14:02
Please c/p the output of the following command (run in the build directory): `cmake -LAH ..`

**Comment by stamerra** [comment] 2017-08-18 21:42
Here it is.  I would like to add that probably there is some mess with the installation of python and other packages (numpy, scipy,...) since I used a bit of pip, then brew and also installe through sources other packages...


`23:19:02 ~/Work/CRPropa3/build> cmake -LHA ..    
-- Build Type: Release
-- CRPropa version: 3.1-45-g439ea6c 439ea6c33e6524e4a5007ad46d3970e0631ce808 refs/heads/master
Using provided EIGEN
-- ROOT: Found!
--   CFlags:      -pthread -stdlib=libc++ -m64 -I/Applications/Scientifici/root/include
--   Libs:        -L/Applications/Scientifici/root/lib -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lpthread -Wl,-rpath,/Applications/Scientifici/root/lib -stdlib=libc++ -lm -ldl
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) (found version "1.0")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) (found version "1.0")
-- Google perftools: NOT Found!
--   Include: GOOGLE_PERFTOOLS_INCLUDE_DIR-NOTFOUND
-- FFTW3 with single precision (FFTW3F): NOT Found!
--   Include:     FFTW3F_INCLUDE_DIR-NOTFOUND
--   Library:     FFTW3F_LIBRARY-NOTFOUND
-- Quimby: NOT Found!
--   Include:     QUIMBY_INCLUDE_DIR-NOTFOUND
--   Library:     QUIMBY_LIBRARY-NOTFOUND
-- SAGA: NOT Found!
--   Include:     SAGA_INCLUDE_DIR-NOTFOUND
--   Library:     SAGA_LIBRARY-NOTFOUND
-- muParser: NOT Found!
--   Include:     MUPARSER_INCLUDE_DIR-NOTFOUND
--   Library:     MUPARSER_LIBRARY-NOTFOUND
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Use absolute RPATH /Users/antonio/.virtualenvs/crpropa/lib
-- Downloading data file from crpropa.desy.de ~ 50 MB
-- Extracting data file
-- Using user provided Python library: /usr/lib/libpython2.7.dylib
-- Python: Found!
--   Version:     2.7/27
--   Executeable: /usr/local/bin/python
--   Include:     /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7
--   Library:     /usr/lib/libpython2.7.dylib
--   Site-package directory: /Users/antonio/.virtualenvs/crpropa/lib/python2.7/site-packages
-- Found numpy headers in /Users/antonio/Library/Python/2.7/lib/python/site-packages/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/antonio/Work/CRPropa3/build
 `

**Comment by adundovi** [comment] 2017-08-19 22:00
Mentioned Python packages shouldn't be the cause of the problem. If numpy is installed cmake will enable additional features in CRPropa automatically, otherwise it will just disable them. Other packages do not influence the installation in any way.

The problem lies during the SWIG interface compilation:
```
swig error : Unrecognized option /usr/include
swig error : Unrecognized option /usr/local/opt/szip/include
```
I would guess that cmake finds a wrong swig binary: check if you have several swig executables on your system and point cmake to use the right one (use -D flag in cmake and [these variables](https://cmake.org/cmake/help/v3.0/module/FindSWIG.html)). I see that you use paths for a python virtual environment but the system python was found during the configuration - did you activate the environment before running cmake and make?

**Comment by stamerra** [comment] 2017-08-24 08:42
I tried different paths, but did not succeed yet.
I found that the library in cmake pointed to python 3.5, so I removed the directory to 3.5; now all libraries point to 2.7.
I removed and reinstalled SWIG removing all virtual links.
I also used the scripts deploy_crpropa.sh and the other called by it, but I continue to have the same error. 
As suggested I also tried to point to the (only one I found) version of swig with option -D.

**Comment by TobiasWinchen** [comment] 2017-10-26 14:57
I assume this issue is fixed by now - If not, please reopen.

**Closed by TobiasWinchen** 2017-10-26 14:57 UTC
Labels: question

**Comment by josinaschulte** [comment] 2019-04-04 10:23
I have exactly the same error while installing CRPropa on Mac OsX 10.14.4.

`swig error : Unrecognized option /usr/local/opt/szip/include`
`Use 'swig -help' for available options.`
`make[2]: *** [crpropa_wrap.cxx] Error 1`
`make[1]: *** [CMakeFiles/crpropa-swig.dir/all] Error 2`


I have:

SWIG Version 3.0.12
Compiled with clang++ [x86_64-apple-darwin18.0.0]
Configured options: +pcre

and for gcc:

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin



When I `cmake -LAH ..` in the build directory, I get the following output. In the CMake configure file I changed the python paths to direct to python 3.7 (I want to use python 3). But here python 2 is found...

-- Build Type: Release
-- CRPropa version: -128-NOTFOUND f6f818d36a64f81a75f7826871926f4ee950e03a refs/heads/master
Using provided EIGEN
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
-- Google perftools: NOT Found!
--   Include: GOOGLE_PERFTOOLS_INCLUDE_DIR-NOTFOUND
-- FFTW3 with single precision (FFTW3F): Found!
--   Include:     /usr/local/include
--   Library:     /usr/local/lib/libfftw3f.dylib
-- SAGA: NOT Found!
--   Include:     SAGA_INCLUDE_DIR-NOTFOUND
--   Library:     SAGA_LIBRARY-NOTFOUND
-- muParser: NOT Found!
--   Include:     MUPARSER_INCLUDE_DIR-NOTFOUND
--   Library:     MUPARSER_LIBRARY-NOTFOUND
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Use absolute RPATH /Users/Josina/Documents/Physik/Master/Masterarbeit/software/CRPropa3/install/lib
-- Downloading data file from crpropa.desy.de ~ 50 MB
-- Extracting data file
-- Using user provided Python library: /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
-- Python: Found!
--   Version:     2.7/27
--   Executeable: /usr/bin/python
--   Include:     /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
--   Library:     /Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
--   Site-package directory: /Users/Josina/Documents/Physik/Master/Masterarbeit/software/CRPropa3/install/lib/python2.7/site-packages
-- Found numpy headers in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Josina/Documents/Physik/Master/Masterarbeit/software/CRPropa3/build
-- Cache values
// Path to a program.
CMAKE_AR:FILEPATH=/usr/bin/ar

// Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=

// Enable/Disable color output during build.
CMAKE_COLOR_MAKEFILE:BOOL=ON

// CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

// Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=

// Flags used by the CXX compiler during DEBUG builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=-g

// Flags used by the CXX compiler during MINSIZEREL builds.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

// Flags used by the CXX compiler during RELEASE builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

// Flags used by the CXX compiler during RELWITHDEBINFO builds.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

// C compiler
CMAKE_C_COMPILER:FILEPATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc

// Flags used by the C compiler during all build types.
CMAKE_C_FLAGS:STRING=

// Flags used by the C compiler during DEBUG builds.
CMAKE_C_FLAGS_DEBUG:STRING=-g

// Flags used by the C compiler during MINSIZEREL builds.
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

// Flags used by the C compiler during RELEASE builds.
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

// Flags used by the C compiler during RELWITHDEBINFO builds.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

// Flags used by the linker during all build types.
CMAKE_EXE_LINKER_FLAGS:STRING=

// Flags used by the linker during DEBUG builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=

// Flags used by the linker during MINSIZEREL builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=

// Flags used by the linker during RELEASE builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=

// Flags used by the linker during RELWITHDEBINFO builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

// Enable/Disable output of compile commands during generation.
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF

// Fortran compiler
CMAKE_Fortran_COMPILER:FILEPATH=/usr/local/bin/gfortran

// A wrapper around 'ar' adding the appropriate '--plugin' option for the GCC compiler
CMAKE_Fortran_COMPILER_AR:FILEPATH=/usr/local/bin/gcc-ar-8

// A wrapper around 'ranlib' adding the appropriate '--plugin' option for the GCC compiler
CMAKE_Fortran_COMPILER_RANLIB:FILEPATH=/usr/local/bin/gcc-ranlib-8

// Flags used by the Fortran compiler during all build types.
CMAKE_Fortran_FLAGS:STRING=

// Flags used by the Fortran compiler during DEBUG builds.
CMAKE_Fortran_FLAGS_DEBUG:STRING=-g

// Flags used by the Fortran compiler during MINSIZEREL builds.
CMAKE_Fortran_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG -Os

// Flags used by the Fortran compiler during RELEASE builds.
CMAKE_Fortran_FLAGS_RELEASE:STRING=-O3 -DNDEBUG -O3

// Flags used by the Fortran compiler during RELWITHDEBINFO builds.
CMAKE_Fortran_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

// Path to a program.
CMAKE_INSTALL_NAME_TOOL:FILEPATH=/usr/bin/install_name_tool

// Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/Users/Josina/Documents/Physik/Master/Masterarbeit/software/CRPropa3/install

// Path to a program.
CMAKE_LINKER:FILEPATH=/usr/bin/ld

// Path to a program.
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make

// Flags used by the linker during the creation of modules during all build types.
CMAKE_MODULE_LINKER_FLAGS:STRING=

// Flags used by the linker during the creation of modules during DEBUG builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=

// Flags used by the linker during the creation of modules during MINSIZEREL builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=

// Flags used by the linker during the creation of modules during RELEASE builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=

// Flags used by the linker during the creation of modules during RELWITHDEBINFO builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

// Path to a program.
CMAKE_NM:FILEPATH=/usr/bin/nm

// Path to a program.
CMAKE_OBJCOPY:FILEPATH=CMAKE_OBJCOPY-NOTFOUND

// Path to a program.
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump

// Build architectures for OSX
CMAKE_OSX_ARCHITECTURES:STRING=

// Minimum OS X version to target for deployment (at runtime); newer APIs weak linked. Set to empty string for default value.
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=

// The product will be built against the headers and libraries located inside the indicated SDK.
CMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk

// Path to a program.
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib

// Flags used by the linker during the creation of shared libraries during all build types.
CMAKE_SHARED_LINKER_FLAGS:STRING=

// Flags used by the linker during the creation of shared libraries during DEBUG builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=

// Flags used by the linker during the creation of shared libraries during MINSIZEREL builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=

// Flags used by the linker during the creation of shared libraries during RELEASE builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=

// Flags used by the linker during the creation of shared libraries during RELWITHDEBINFO builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=

// If set, runtime paths are not added when installing shared libraries, but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO

// If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=NO

// Flags used by the linker during the creation of static libraries during all build types.
CMAKE_STATIC_LINKER_FLAGS:STRING=

// Flags used by the linker during the creation of static libraries during DEBUG builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

// Flags used by the linker during the creation of static libraries during MINSIZEREL builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

// Flags used by the linker during the creation of static libraries during RELEASE builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

// Flags used by the linker during the creation of static libraries during RELWITHDEBINFO builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

// Path to a program.
CMAKE_STRIP:FILEPATH=/usr/bin/strip

// If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE

// Download CRProap Data files
DOWNLOAD_DATA:BOOL=ON

// Dot tool for use with Doxygen
DOXYGEN_DOT_EXECUTABLE:FILEPATH=/usr/local/bin/dot

// Doxygen documentation generation tool (http://www.doxygen.org)
DOXYGEN_EXECUTABLE:FILEPATH=DOXYGEN_EXECUTABLE-NOTFOUND

// Use EIGEN from this path instead of the version shipped with CRPropa
EIGEN_PATH:STRING=

// Add code for coverage analysis.
ENABLE_COVERAGE:BOOL=OFF

// Galactic Magnetic Lens
ENABLE_GALACTICMAGETICLENS:BOOL=ON

// Embedding information about CRPropa version from git
ENABLE_GIT:BOOL=ON

// HDF5 Support
ENABLE_HDF5:BOOL=ON

// OpenMP for multithreading
ENABLE_OPENMP:BOOL=ON

// Create python library via SWIG
ENABLE_PYTHON:BOOL=ON

// Quimby Support
ENABLE_QUIMBY:BOOL=OFF

// Use SWIG's -builtin option
ENABLE_SWIG_BUILTIN:BOOL=ON

// Build tests and enable test target
ENABLE_TESTING:BOOL=ON

// Path to a file.
FFTW3F_INCLUDE_DIR:PATH=/usr/local/include

// Path to a library.
FFTW3F_LIBRARY:FILEPATH=/usr/local/lib/libfftw3f.dylib

// Git command line client
GIT_EXECUTABLE:FILEPATH=/usr/local/bin/git

// Path to a file.
GOOGLE_PERFTOOLS_INCLUDE_DIR:PATH=GOOGLE_PERFTOOLS_INCLUDE_DIR-NOTFOUND

// HDF5 C Wrapper compiler.  Used only to detect HDF5 compile flags.
HDF5_C_COMPILER_EXECUTABLE:FILEPATH=/usr/local/bin/h5cc

// Path to a library.
HDF5_C_LIBRARY_dl:FILEPATH=/usr/lib/libdl.dylib

// Path to a library.
HDF5_C_LIBRARY_hdf5:FILEPATH=/usr/local/Cellar/hdf5/1.10.5/lib/libhdf5.dylib

// Path to a library.
HDF5_C_LIBRARY_m:FILEPATH=/usr/lib/libm.dylib

// Path to a library.
HDF5_C_LIBRARY_sz:FILEPATH=/usr/local/opt/szip/lib/libsz.dylib

// Path to a library.
HDF5_C_LIBRARY_z:FILEPATH=/usr/lib/libz.dylib

// HDF5 file differencing tool.
HDF5_DIFF_EXECUTABLE:FILEPATH=/usr/local/bin/h5diff

// The directory containing a CMake configuration file for HDF5.
HDF5_DIR:PATH=HDF5_DIR-NOTFOUND

// Install provided EIGEN headers
INSTALL_EIGEN:BOOL=OFF

// Path to a file.
MUPARSER_INCLUDE_DIR:PATH=MUPARSER_INCLUDE_DIR-NOTFOUND

// Path to a library.
MUPARSER_LIBRARY:FILEPATH=MUPARSER_LIBRARY-NOTFOUND

// FORMAT type,chunksize
OMP_SCHEDULE:STRING=static,100

// CXX compiler flags for OpenMP parallelization
OpenMP_CXX_FLAGS:STRING=NOTFOUND

// CXX compiler libraries for OpenMP parallelization
OpenMP_CXX_LIB_NAMES:STRING=NOTFOUND

// C compiler flags for OpenMP parallelization
OpenMP_C_FLAGS:STRING=NOTFOUND

// C compiler libraries for OpenMP parallelization
OpenMP_C_LIB_NAMES:STRING=NOTFOUND

// Fortran compiler flags for OpenMP parallelization
OpenMP_Fortran_FLAGS:STRING=-fopenmp

// Fortran compiler libraries for OpenMP parallelization
OpenMP_Fortran_LIB_NAMES:STRING=gomp

// Path to the gomp library for OpenMP
OpenMP_gomp_LIBRARY:FILEPATH=/usr/local/Cellar/gcc/8.3.0/lib/gcc/8/libgomp.dylib

// pkg-config executable
PKG_CONFIG_EXECUTABLE:FILEPATH=/usr/local/bin/pkg-config

// Path to a library.
PROFILER_LIBRARY:FILEPATH=PROFILER_LIBRARY-NOTFOUND

// Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python

// Path to a file.
PYTHON_H_FOUND:FILEPATH=/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h

// Path to a file.
PYTHON_INCLUDE_DIR:PATH=/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m

// Path to a library.
PYTHON_LIBRARY:FILEPATH=/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib

// Path to a library.
PYTHON_LIBRARY_DEBUG:FILEPATH=PYTHON_LIBRARY_DEBUG-NOTFOUND

// Path to a file.
QUIMBY_INCLUDE_DIR:PATH=QUIMBY_INCLUDE_DIR-NOTFOUND

// Path to a library.
QUIMBY_LIBRARY:FILEPATH=QUIMBY_LIBRARY-NOTFOUND

// Path to a file.
SAGA_INCLUDE_DIR:PATH=SAGA_INCLUDE_DIR-NOTFOUND

// Path to a library.
SAGA_LIBRARY:FILEPATH=SAGA_LIBRARY-NOTFOUND

// Path to a library.
STACKTRACE_LIBRARY:FILEPATH=STACKTRACE_LIBRARY-NOTFOUND

// Path to a file.
SWIG_DIR:PATH=/usr/local/Cellar/swig/3.0.12/share/swig/3.0.12

// Path to a program.
SWIG_EXECUTABLE:FILEPATH=/usr/local/bin/swig

// Swig version
SWIG_VERSION:STRING=3.0.12

// Path to a library.
TCMALLOC_LIBRARY:FILEPATH=TCMALLOC_LIBRARY-NOTFOUND

// Add absolute rpath to all libraries and executables
USE_ABSOLUTE_RPATH:BOOL=ON

// Path to a file.
ZLIB_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include

// Path to a library.
ZLIB_LIBRARY_DEBUG:FILEPATH=ZLIB_LIBRARY_DEBUG-NOTFOUND

// Path to a library.
ZLIB_LIBRARY_RELEASE:FILEPATH=/usr/lib/libz.dylib
